version: "3.8"

services:
  frontend:
    build:
      context: frontend
      target: development
    image: image-frontend
    container_name: container-frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
